#!/bin/bash
echo "=========================================="
echo "   Kyaf Edu - Logiciel de gestion scolaire"
echo "=========================================="
echo ""
echo "L'application va demarrer..."
echo ""
echo "Une fois lancee, ouvre ton navigateur et va sur :"
echo ""
echo "    http://127.0.0.1:5000"
echo ""
echo "Identifiant : admin"
echo "Mot de passe : admin123"
echo ""
echo "Pour arreter l'application, appuie sur Ctrl + C"
echo "=========================================="
echo ""
cd "$(dirname "$0")"
python3 app.py
